Improve di-handle behavior
CMU-cabot/cabot-navigation pull request #85
Opened 2024-11-12 01:56 UTC by yukiya-gy

ターンの終了検出と、cabot rotation shim controllerによる旋回検出のためにTopicを追加しました。

2024-11-12 15:10 UTC, daisukes requested changes

2024-11-12 15:10 UTC, daisukes commented on cabot_ui/cabot_ui/turn_detector.py
> +# Copyright (c) 2024  ALPS ALPINE CO., LTD.
変更がないようなので、これは削除お願いします。

2024-11-12 23:37 UTC, yukiya-gy commented on cabot_ui/cabot_ui/turn_detector.py
> +# Copyright (c) 2024  ALPS ALPINE CO., LTD.
すみません別のブランチと混同していました。消します。

2024-11-20 03:29 UTC, daisukes approved these changes

2024-11-20 03:41 UTC, daisukes approved these changes

2024-11-20 03:41 UTC, merged