Add crosswalk link
CMU-cabot/cabot-navigation pull request #86
Opened 2024-11-12 05:26 UTC by kimushun1101

横断歩道リンクを作成しました。

cabot_site_testで [kimushun1101/add-crosswalk-link](https://github.com/CMU-cabot/cabot_sites_test/tree/kimushun1101/add-crosswalk-link) ブランチを作り、横断歩道リンクを追加したMapdata.jsonに記述しました。
シミュレーターで動作確認しております。

## テスト実行手順

.env
```
CABOT_MODEL=cabot2-gt1
CABOT_SITE=cabot_site_test_room
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
CYCLONEDDS_URI=/home/developer/cyclonedds_spdp.xml
CABOT_SHOW_GAZEBO_CLIENT=1 
```

ターミナル1
```
cd ~/cabot/cabot-navigation
git switch cabot-navigation/kimushun1101/add-crosswalk-link
cd ~/cabot/cabot-navigation/cabot_sites/cabot_sites_test
git switch kimushun1101/add-crosswalk-link
cd ~/cabot
./build-docker -w navigation
./launch.sh -s -S cabot_site_test_room
```

ターミナル2
```
docker compose exec navigation bash
# docker内
./script/run_test.sh tests test20_crosswalk
```

2024-11-12 06:08 UTC, daisukes approved these changes

2024-11-12 15:22 UTC, daisukes requested changes

2024-11-12 15:22 UTC, daisukes commented on cabot_ui/cabot_ui/geojson.py
> +# Copyright (c) 2020, 2022, 2024  Carnegie Mellon University and Miraikan
2020, 2024　（作った年、更新年）でお願いします。

2024-11-13 00:13 UTC, kimushun1101 commented on cabot_ui/cabot_ui/geojson.py
> +# Copyright (c) 2020, 2022, 2024  Carnegie Mellon University and Miraikan
ありがとうございます。勘違いしておりました。

2024-11-20 02:01 UTC, kenconnor commented
メモ
段差昇降モードの実装によってコンフリクトが発生する部分をブランチにまとめました。
https://github.com/CMU-cabot/cabot-navigation/tree/kenconnor/add-climbing-step

2024-11-20 04:33 UTC, daisukes commented
@kimushun1101 

一旦この変更でマージして良いでしょうか？squashでdevに入れます。
続きを開発する場合はdevからブランチを切った方が良いです。
下記patchも参考に、横断歩道、単純な段差（万博に段差があるかは不明）について、方針の相談・決定をお願いします…

@kenconnor 

climbup の変更をマージしようと思ったのですが、そのままマージするのは無理がありそうなので、devには入れません。
obstacle-pluginのPRから消された部分のみをlocalでrevertしてパッチにしました

[clibmup.patch](https://github.com/user-attachments/files/17824820/clibmup.patch)

2024-11-20 04:34 UTC, daisukes approved these changes

2024-11-20 04:34 UTC, merged